---
- name: Instalando PHP y modulos requeridos
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - php7.0-json
    - php7.0-mbstring
    - php7.0-intl
    - libapache2-mod-php7.0

- name: Instalando Apache
  apt:
    name: apache2
    state: present

- name: Iniciando servicio Apache
  service:
    name: apache2
    state: started
